services:
  - type: web
    name: agent-trading
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
      - key: GOOGLE_SPREADSHEET_ID
        sync: false
      - key: GOOGLE_SHEET_NAME_WATCHLIST
        value: "Suivi d'Investissement"
      - key: GOOGLE_SHEET_NAME_SIGNALS
        value: "Signaux"
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
